### PR TITLE
Fix conflict with Gravity Forms Stripe Add-on

### LINKED ISSUE #22: Possible conflict with the Stripe add-on
Report from a user:
> With the recent update to Gravity Forms Stripe add-on 5.1.0, we ran into an issue. 
> 
> Once enabling the Alternate Payment Methods (for Apple/Google Pay, etc). Entries were getting flagged as spam, yet they were getting charged, but the entry process was not completed to provide updated data for the entry, such as the payment ID, process Mailchimp, and Zapier feeds, or send the notification emails to the customer and us.
> 
> When disabling your plugin, everything works fine (except now we are getting spam submissions on our non-payment forms).
> 
> I've been working with the GF support team on issues around Stripe 5.0 and 5.1, and when I reported this information to them, they suggested that I submit this information to you to investigate a potential conflict between the Stripe 5.1.0 add-on and Gravity Forms Zero Spam.

### PR DESCRIPTION
**Pull request by malayladu**
**Issue**

With the recent update to Gravity Forms Stripe add-on 5.1.0, once enabling the Alternate Payment Methods (for Apple/Google Pay, etc). Entries were getting flagged as spam

**Expected Behaviour**

Entries should not marked as spam. 

Fixes #22

### CODE REVIEW

File: gravityforms-zero-spam.php [hunk 1]
```diff
@@ -97,7 +122,7 @@ public function add_key_field( $form ) {
 		$autocomplete = RGFormsModel::is_html5_enabled() ? ".attr( 'autocomplete', 'new-password' )\n\t\t" : '';
 
 		$script = <<<EOD
-jQuery( document ).on( 'submit.gravityforms', '.gform_wrapper form', function( event ) {
+jQuery( "#gform_{$form['id']}" ).on( 'submit', function( event ) {
```
Comment (zackkatz) [inline gravityforms-zero-spam.php:125]: @malayladu Does the fix not work unless we use the jQuery selector? If so, please add a docblock mentioning that. If the GF hook does work, let’s keep it to prevent changing more than necessary.
